knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Twitter Bootstrap v4 template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Sortable link template
    page_range: 5                      # Number of pages to display in pagination
    default_options:
        page_name: page                # Name of the page parameter in the URL
        sort_field_name: sort          # Name of the sort field parameter in the URL
        sort_direction_name: direction # Name of the sort direction parameter in the URL
        distinct: true 