#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

get_reservations:
    path: '/reservations'
    controller: 'App\Controller\ReservationController::getReservations'
    methods: ['GET']

