index:
    path: /
    controller: App\Controller\HomeController::index

get_reservations:
    path: '/reservations'
    controller: 'App\Controller\ReservationController::getReservations'
    methods: ['GET']

game_js:
    path: /game.js
    controller: Symfony\Component\HttpKernel\Controller\BinaryFileController::index
    defaults:
        path: '%kernel.project_dir%/public/game.js'
